// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzULeLVDl3ixtrYDRAXdUg3UyvwEoskq4',
    appId: '1:206112234935:web:4d82d7e388c51a0d71dc32',
    messagingSenderId: '206112234935',
    projectId: 'etechstorage-87e4a',
    authDomain: 'etechstorage-87e4a.firebaseapp.com',
    storageBucket: 'etechstorage-87e4a.firebasestorage.app',
    measurementId: 'G-7V41MF7FFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsC387YEXs-IiT3ng1iHDwA9dqzKAaZyk',
    appId: '1:206112234935:android:787124d0678506f971dc32',
    messagingSenderId: '206112234935',
    projectId: 'etechstorage-87e4a',
    storageBucket: 'etechstorage-87e4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmZ5k5IDut2RIm0XJvxz-eH61vkfh3kpU',
    appId: '1:206112234935:ios:27984b342b2017f571dc32',
    messagingSenderId: '206112234935',
    projectId: 'etechstorage-87e4a',
    storageBucket: 'etechstorage-87e4a.firebasestorage.app',
    iosBundleId: 'com.example.etech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmZ5k5IDut2RIm0XJvxz-eH61vkfh3kpU',
    appId: '1:206112234935:ios:27984b342b2017f571dc32',
    messagingSenderId: '206112234935',
    projectId: 'etechstorage-87e4a',
    storageBucket: 'etechstorage-87e4a.firebasestorage.app',
    iosBundleId: 'com.example.etech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzULeLVDl3ixtrYDRAXdUg3UyvwEoskq4',
    appId: '1:206112234935:web:00de5f3de670e3bd71dc32',
    messagingSenderId: '206112234935',
    projectId: 'etechstorage-87e4a',
    authDomain: 'etechstorage-87e4a.firebaseapp.com',
    storageBucket: 'etechstorage-87e4a.firebasestorage.app',
    measurementId: 'G-MRCBP7TNNG',
  );
}
